services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=suasenha
      - POSTGRES_USER=seuusuario
      - POSTGRES_DB=seubanco
    ports:
      - 5432:5432

